pipeline {
  agent {
    docker { image 'nginx:latest' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx -version'
        sh 'docker container ls  | grep nginx | awk "{print $1}"'
        sh 'echo "Yes, Abishek you did it nginx is working perfectly hurrayyyyy......."'
      }
    }
  }
}
