pipeline {
  agent {
    docker { image 'nginx:latest' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'nginx -version'
        sh 'sleep 50'
        sh 'curl localhost'
        sh 'echo "Yes, Abishek you did it nginx is working perfectly hurrayyyyy......."'
      }
    }
  }
}
